apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: greencap-demo
  labels:
    app.kubernetes.io/managed-by: greencap
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
